[project]
name = "template-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "myagent",
    "fs>=2.4.16",
]

[tool.uv.sources]
myagent = { git = "https://github.com/JasonDZS/myagent.git", rev = "v0.1.2" }
